### ISSUE TITLE
Sofaros tuto

### ISSUE THREAD

**Issue by samFabrice** [SofaDefrost/SoftRobots#109]
Hello @EulalieCoevoet ,
I'm trying to do the sofaRos tutorial but I got an error .
I compiled SOFA with SOFAPython3 and I use the rolling version of ros2.

when I run the test_sofaros.py file
 with runSofa I have this error : 

ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
The C extension '/opt/ros/rolling/lib/python3.8/site-packages/_rclpy_pybind11.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions

Which is normal because  sofaPython3 uses python3.9 and ros2 uses python3.8 which causes the import error due to version incompatibility
 

The problem is that I can't compile sofa with sofaPython3 using python3.8

Can you help me please?

**Comment by EulalieCoevoet** [comment]
Hi @samFabrice, 

I'm already trying to help Tori [here](https://github.com/SofaDefrost/SoftRobots/discussions/105) using the Discussion tool. Maybe you can have a look at this [comment](https://github.com/SofaDefrost/SoftRobots/discussions/105#discussioncomment-2275598) because I believe that changing your default python to python3.8 can be a fix since you're compiling SOFA. 
I don't see why you couldn't compile SofaPython3 with python3.8.

I don't think there is an *issue* with the plugin SoftRobots so I propose to close this issue.

Eulalie
