### ISSUE TITLE
SoftRobots plugin must not refer SoftRobots.Inverse plugin

### ISSUE THREAD

**Issue by alxbilger** [SofaDefrost/SoftRobots#144]
A lot of scenes from the SoftRobots plugin refer the SoftRobots.Inverse plugin through the `RequiredPlugin` component. Yet, the SoftRobots.Inverse plugin depends on SoftRobots, but not the opposite.

- If the scene does not need SoftRobots.Inverse, it should be removed from the required plugin lists
- If the scene does need SoftRobots.Inverse, the scene should be: 1) transferred to the SoftRobots.Inverse plugin, or 2) transformed to remove the dependency.

**Comment by EulalieCoevoet** [comment]
I went through the docs folder and didn't find any unnecessary `RequiredPlugin`. 
I still think that the inverse steps of our tutorials belong in this repository. However, I came across three other simulations using the inverse resolution. I've set it as an option (false by default). I think we should keep the option because in each case it's a really nice demonstration/feature/example of use.

**Comment by EulalieCoevoet** [comment]
@alxbilger Should we close this issue ?
